name: cloud_firestore_odm_example
publish_to: none

environment:
  sdk: '>=3.6.0-edge <4.0.0'

dependencies:
  cloud_firestore: ^4.7.15
  cloud_firestore_odm:
    git:
      url: https://github.com/lirantzairi/firestoreodm-flutter.git
      ref: dev
      path: packages/cloud_firestore_odm
  firebase_core: 3.9.0
  flutter:
    sdk: flutter
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  meta: 1.15.0

dev_dependencies:
  build_runner: 2.4.14
  cloud_firestore_odm_generator:
    path: ../../cloud_firestore_odm_generator
  cloud_firestore_odm_generator_integration_test:
    path: ../../cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test
  flutter_test:
    sdk: flutter
  freezed: 3.0.0-0.0.dev
  http: 1.2.2
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.0
  mockito: 5.4.5

flutter:
  uses-material-design: true
