name: cloud_firestore_odm_generator
description: A code generator for cloud_firestore_odm.
version: 1.0.0-dev.86

environment:
  sdk: '>=3.6.0-edge <4.0.0'

dependencies:
  analyzer: ">=5.12.0 <7.0.0"
  build: 2.4.2
  build_config: 1.1.2
  cloud_firestore_odm:
    path: ../cloud_firestore_odm
  collection: 1.19.0
  freezed_annotation: 2.4.4
  # Can be removed once this is fixed https://github.com/dart-lang/graphs/issues/86
  graphs: 2.3.2
  json_annotation: 4.9.0
  meta: 1.15.0
  recase: 4.1.0
  source_gen: 1.4.0
  source_helper: 1.3.5

dev_dependencies:
  build_runner: 2.4.14
  expect_error: 1.0.7
  json_serializable: 6.9.0
  matcher: 0.12.16+1
  test: 1.25.8
