name: cloud_firestore_odm
description: An ODM for Firebase Cloud Firestore (cloud_firestore).
homepage: https://github.com/firebaseextended/firestoreodm-flutter
repository: https://github.com/firebaseextended/firestoreodm-flutter
version: 1.0.0-dev.84

false_secrets:
  - example/**

environment:
  sdk: '>=3.6.0-edge <4.0.0'

dependencies:
  cloud_firestore: ^5.6.0
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
