name: cloud_firestore_odm_generator_integration_test
publish_to: none

environment:
  sdk: '>=3.6.0-edge <4.0.0'

dependencies:
  cloud_firestore: ^4.15.0
  cloud_firestore_odm:
    git:
      url: https://github.com/lirantzairi/firestoreodm-flutter.git
      ref: dev
      path: packages/cloud_firestore_odm
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.2
  cloud_firestore_odm_generator:
    path: ..
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0-0.0.dev
  json_serializable: '>=6.6.1 <7.0.0'

flutter:
  uses-material-design: false
